### ISSUE TITLE
Unable to install from pypi

### ISSUE THREAD

**Issue by a1ext** [isra17/nrs#1]
I tried to install the "nrs" package from pypi in PyCharm and got the following error:

> Collecting nrs
>   Using cached nrs-0.2.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     warning: build_py: byte-compiling is disabled, skipping.
>     
>     warning: install_lib: byte-compiling is disabled, skipping.
>     
>     warning: easy_install: byte-compiling is disabled, skipping.
>     
>     
>     Installed c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs\setuptools_markdown-0.2-py2.7.egg
>     Searching for pytest-runner
>     Reading https://pypi.python.org/simple/pytest-runner/
>     Best match: pytest-runner 2.7.1
>     Downloading https://pypi.python.org/packages/99/6b/c4ff4418d3424d4475b7af60724fd4a5cdd91ed8e489dc9443281f0052bc/pytest-runner-2.7.1.tar.gz#md5=e56f0bc8d79a6bd91772b44ef4215c7e
>     Processing pytest-runner-2.7.1.tar.gz
>     Writing c:\users\alex\appdata\local\temp\easy_install-h8sn9k\pytest-runner-2.7.1\setup.cfg
>     Running pytest-runner-2.7.1\setup.py -q bdist_egg --dist-dir c:\users\alex\appdata\local\temp\easy_install-h8sn9k\pytest-runner-2.7.1\egg-dist-tmp-nlenbk
>     warning: build_py: byte-compiling is disabled, skipping.
>     
>     warning: install_lib: byte-compiling is disabled, skipping.
>     
>     
>     Installed c:\users\alex\appdata\local\temp\easy_install-h8sn9k\pytest-runner-2.7.1\.eggs\setuptools_scm-1.11.0-py2.7.egg
>     warning: build_py: byte-compiling is disabled, skipping.
>     
>     warning: install_lib: byte-compiling is disabled, skipping.
>     
>     zip_safe flag not set; analyzing archive contents...
>     Moving pytest_runner-2.7.1-py2.7.egg to c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs
>     
>     Installed c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs\pytest_runner-2.7.1-py2.7.egg
>     Searching for pypandoc
>     Reading https://pypi.python.org/simple/pypandoc/
>     Best match: pypandoc 1.1.3
>     Downloading https://pypi.python.org/packages/41/68/e985491370cc44a063ac5c70232bf72d7675fa7539a86fa7fa08257bda05/pypandoc-1.1.3.zip#md5=771f376bf9c936a90159cd94235998c2
>     Processing pypandoc-1.1.3.zip
>     Writing c:\users\alex\appdata\local\temp\easy_install-anykgy\pypandoc-1.1.3\setup.cfg
>     Running pypandoc-1.1.3\setup.py -q bdist_egg --dist-dir c:\users\alex\appdata\local\temp\easy_install-anykgy\pypandoc-1.1.3\egg-dist-tmp-jcwbys
>     Patching wheel building...
>     warning: build_py: byte-compiling is disabled, skipping.
>     
>     warning: install_lib: byte-compiling is disabled, skipping.
>     
>     zip_safe flag not set; analyzing archive contents...
>     Moving pypandoc-1.1.3-py2.7.egg to c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs
>     
>     Installed c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs\pypandoc-1.1.3-py2.7.egg
>     Traceback (most recent call last):
>       File "<string>", line 20, in <module>
>       File "C:\Users\alex\AppData\Local\Temp\pycharm-packaging\nrs\setup.py", line 30, in <module>
>         ext_modules=[bzlib, lzma]
>       File "C:\Python27\lib\distutils\core.py", line 111, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "C:\Python27\lib\site-packages\setuptools\dist.py", line 272, in __init__
>         _Distribution.__init__(self,attrs)
>       File "C:\Python27\lib\distutils\dist.py", line 287, in __init__
>         self.finalize_options()
>       File "C:\Python27\lib\site-packages\setuptools\dist.py", line 327, in finalize_options
>         ep.load()(self, ep.name, value)
>       File "c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs\setuptools_markdown-0.2-py2.7.egg\setuptools_markdown.py", line 22, in long_description_markdown_filename
>         output = pypandoc.convert(markdown_filename, 'rst')
>       File "c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs\pypandoc-1.1.3-py2.7.egg\pypandoc\__init__.py", line 50, in convert
>       File "c:\users\alex\appdata\local\temp\pycharm-packaging\nrs\.eggs\pypandoc-1.1.3-py2.7.egg\pypandoc\__init__.py", line 68, in _convert
>     RuntimeError: Missing format!

Win7x64, Python 2.7.10 x86

**Comment by isra17** [comment]
`pypandoc` might have some issue on Windows... This dependancy is not really required, it is only used for fancy README on Pypi from the markdown readme. I will fix it on `master`, but will only be able to push a new Pypi version later.

**Comment by a1ext** [comment]
Thank you

**Comment by isra17** [comment]
Should be fixed with last release. Thanks!
