### ISSUE TITLE
Error with lzma

### ISSUE THREAD

**Issue by DigiAngel** [isra17/nrs#4]
This was working great and now for the life of me I can't get it to work now.  Here's my error:
~~~
Traceback (most recent call last):
  File "nsisdump.py", line 230, in <module>
    dump_all(nsis_target)
  File "nsisdump.py", line 115, in dump_all
    nsis = NSIS.from_path(path)
  File "/opt/nrs/nrs/nsisfile.py", line 18, in from_path
    return NSIS(fd)
  File "/opt/nrs/nrs/nsisfile.py", line 47, in __init__
    if not self._parse():
  File "/opt/nrs/nrs/nsisfile.py", line 137, in _parse
    self.header = fileform._extract_header(self.fd, self.firstheader)
  File "/opt/nrs/nrs/fileform.py", line 302, in _extract_header
    inflated_data, data_size = inflate_header(nsis_file, firstheader.data_offset)
  File "/opt/nrs/nrs/fileform.py", line 294, in inflate_header
    inflated_data = decoder(nsis_file, data_size)
  File "/opt/nrs/nrs/fileform.py", line 263, in _lzma
    props = lzma._decode_filter_properties(lzma.FILTER_LZMA1, data[0:5])
AttributeError: 'module' object has no attribute '_decode_filter_properties'
~~~

and the versions of lzma stuff installed on the box:
~~~
liblzma-dev:amd64 5.2.2-1.2+b1
liblzma5:amd64 5.2.2-1.2+b1
lzma 9.22-2+b3
lzma-dev 9.22-2
python-lzma 0.5.3-3
~~~

anything I can do to troubleshoot this?  Thank you.

**Comment by isra17** [comment]
Ha, might be an issue with Python 2. Will try to look at it quickly. For what it's worth, you can revert on the last version and it should work fine. Latest commits were done to remove native dependancies on lzma.

**Comment by DigiAngel** [comment]
Thank you...this will sound dumb, but that's something I've never done before...how do I revert to the last version?  Thank you...and thanks for this app :)

**Comment by isra17** [comment]
Actually the Pypi version is the old one: `pip uninstall nrs && CFLAGS=-m32 LDFLAGS=-m32 pip install nrs`.
If you cloned from git simple use `git checkout 2514a58797aea0d835e761b48d143e3c4f00599c` from the repository.
It really depends on how you installed it.

**Comment by isra17** [comment]
This message is expected, it should work from there.

**Comment by DigiAngel** [comment]
Alas, same message :(...looks like it's something else:
~~~
commit 2514a58797aea0d835e761b48d143e3c4f00599c
Merge: a70aa22 e89a5c5
Author: Israël Hallé <isra017@gmail.com>
Date:   Fri Oct 28 11:39:42 2016 -0400

    Merge pull request #2 from isra17/fix-readme

    Fix typo in README
~~~
Using python3 I get:
~~~
Traceback (most recent call last):
  File "nsisdump.py", line 230, in <module>
    dump_all(nsis_target)
  File "nsisdump.py", line 115, in dump_all
    nsis = NSIS.from_path(path)
  File "/media/cuckoo/opt/nrs/nrs/nsisfile.py", line 18, in from_path
    return NSIS(fd)
  File "/media/cuckoo/opt/nrs/nrs/nsisfile.py", line 47, in __init__
    if not self._parse():
  File "/media/cuckoo/opt/nrs/nrs/nsisfile.py", line 137, in _parse
    self.header = fileform._extract_header(self.fd, self.firstheader)
  File "/media/cuckoo/opt/nrs/nrs/fileform.py", line 301, in _extract_header
    inflated_data, data_size = inflate_header(nsis_file, firstheader.data_offset)
  File "/media/cuckoo/opt/nrs/nrs/fileform.py", line 293, in inflate_header
    inflated_data = decoder(nsis_file, data_size)
  File "/media/cuckoo/opt/nrs/nrs/fileform.py", line 261, in _lzma
    from nrs.ext import lzma
  File "/media/cuckoo/opt/nrs/nrs/ext/lzma/__init__.py", line 1, in <module>
    from .lzma import *
ImportError: No module named 'nrs.ext.lzma.lzma'
~~~

Thank you.

**Comment by isra17** [comment]
Ha, you need to build again, would be simpler to uninstall and reinstall:
`pip uninstall nrs && CFLAGS=-m32 LDFLAGS=-m32 pip install -e /media/cuckoo/opt/nrs/`

**Comment by DigiAngel** [comment]
Ah...I see here.  I never built it and installed it...just git cloned and ran the script from the nrs dir...would that make the difference?

**Comment by isra17** [comment]
Yes, there are some C library shipped with the project that needs to be
compiled first. The latest patch was to remove one of them, but seems like
lzma is not distributed with all python version.

**Comment by DigiAngel** [comment]
Ok cool...built, installed, but same issue.  Maybe Debian packages things weird.  I'll try and get this setup on a different distro and report my findings...thank you.

**Comment by DigiAngel** [comment]
needs pip3 and python3 :)
